---
title: "La place de la femme dans la profession informatique"
author: "Elise Hodbert, Nolwenn Paquet, Victoria Bancel"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    orientation: columns
    vertical_layout: fill
    navbar:
      - { title: "Moodle", href: "https://tice.agrocampus-ouest.fr/course/view.php?id=6726", align: left }
      - { icon: "fa-twitter", href: "https://twitter.com/marie_etienne", align: right }
      - { icon: "fa-linkedin", href: "https://www.linkedin.com/in/marie-etienne-818a7115/", align: right }
params:
  setup_path: ../resources/
---

<style>                     
.navbar {
  background-color:#46ACC8;
  border-color:#46ACC8;
}
.navbar-brand {
color:black!important;
}


</style>   


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### An easy solution for dashboard

Le [lien](https://rmarkdown.rstudio.com/flexdashboard/index.html) renvoie à l'étude réalisée en.

### Répartition des hommes et des femmes dans les

```{r data, eval = TRUE, echo = FALSE, results='hide', message = FALSE, warning=FALSE}
n <- 100
dta <- tibble(size = round(rnorm(n, mean = 0, sd =10),2), 
           color = sample(x= c('Blue', 'Yellow'), size = n, replace = TRUE))

```


```{r graph_static,  echo = FALSE,  message = FALSE, warning=FALSE}
p1 <- dta %>% ggplot() +
  aes(x=color, y = size) +
  geom_boxplot(aes(fill= color))
p1
```

Column {.tabset .tabset-fade}
-----------------------------------------------------------------------


### Some dynamic maps

```{r  ggplotly, echo = TRUE,  eval = TRUE,  message = FALSE, warning=FALSE}
plotly::ggplotly(p1)
```



### Chart C

```{r}

```

